services:
  # caddy:
  #   image: caddy:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./tmp/caddy/caddy_config:/config
  #     - ./tmp/caddy/caddy_data:/data
  #     - ./tmp/caddy/caddy_file:/etc/caddy/Caddyfile
  #   networks:
  #     - wekan-tier
  #   environment:
  #     - ACME_AGREE=true

  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan-app
    restart: always

    networks:
      - wekan-tier
    ports:
      - 5000:8080
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      - WRITABLE_PATH=/data
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    depends_on:
      - wekandb
    volumes:
      - wekan-files:/data:rw

volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
